func foo() {
  self; // expect error
}
